name: Run Nightly Consul Pipeline

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      service_branch:
        description: 'Branch to run tests against'
        required: false
        default: 'main'
      skip_wait:
        description: 'Skip waiting for dev_build.yml to complete (use when images are already built)'
        required: false
        type: boolean
        default: false
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "CODE-OF-CONDUCT.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "README.md"
      - "SECURITY.md"

jobs:
  Nightly-Consul-Pipeline:
    uses: Netcracker/qubership-test-pipelines/.github/workflows/consul.yaml@247c69038e00f2a9e283412e902555f84b16dab2 # v1.8.0
    with:
      service_branch: 'main'
      pipeline_branch: '247c69038e00f2a9e283412e902555f84b16dab2' # v1.8.0 renovate: depName=Netcracker/qubership-test-pipelines
      scope: 'nightly'
    secrets:
      AWS_S3_ACCESS_KEY_ID: ${{secrets.AWS_S3_ACCESS_KEY_ID}}
      AWS_S3_ACCESS_KEY_SECRET: ${{secrets.AWS_S3_ACCESS_KEY_SECRET}}
